### ISSUE TITLE
Ansi escape codes

### ISSUE THREAD

**Issue by refaelsh** [jtdaugherty/text-zipper#13]
Hi @jtdaugherty, fancy meeting you here :-)

I was googling why my TextZipper does not print certain characters and wounded up here :-)
Maybe related to this: https://github.com/jtdaugherty/text-zipper/issues/9.

When I use `insertMany` to insert the following:
```haskell
bla = "111\x1b[1;31mHello"
```
I only see 111 on screen. I expected to see something like `111[1;31Hello` because `\x1b` is not a printable character.
But it seems to stop at unprintable characters instead of skipping them.

**Comment by refaelsh** [comment]
Also, when I use `stringZipper` with the above-mentioned string, everything is fine.

**Comment by jtdaugherty** [comment]
I've confirmed that the character insertion does indeed stop at a non-printable character, which wasn't my intention. I still would encourage you not to even attempt doing what you're doing, but I'm going to fix the insertion routine to filter out the characters rather than causing it to stop insertion of the whole string. Thanks for reporting this!

**Comment by jtdaugherty** [comment]
I've fixed both issues you mentioned above. The fixes are on `master`.

**Comment by jtdaugherty** [comment]
The fixes are now released in `0.13`.

**Comment by refaelsh** [comment]
Just tried it. It works now as expected. Thank you :-)
